services:
    bd_guzzle_site_authenticator.authenticator_subscriber:
        class: BD\GuzzleSiteAuthenticatorBundle\Guzzle\AuthenticatorSubscriber
        arguments:
            - @bd_guzzle_site_authenticator.site_config_builder
            - @bd_guzzle_site_authenticator.authenticator_factory

    bd_guzzle_site_authenticator.site_config_builder:
        alias: bd_guzzle_site_authenticator.site_config_builder.array

    bd_guzzle_site_authenticator.site_config_builder.array:
        class: BD\GuzzleSiteAuthenticatorBundle\SiteConfig\ArraySiteConfigBuilder

    bd_guzzle_site_authenticator.authenticator_factory:
        class: BD\GuzzleSiteAuthenticatorBundle\Authenticator\Factory
        arguments:
            - @bd_guzzle_site_authenticator.credentials_bag

    bd_guzzle_site_authenticator.credentials_bag:
        class: BD\GuzzleSiteAuthenticatorBundle\Authenticator\CredentialsBag\ArrayCredentialsBag
        arguments:
            -
                "mediapart.fr": {"username": "%mediapart_login%", "password": "%mediapart_password%"}
